### ISSUE TITLE
Safari does not correctly display compass (rotations, etc.)

### ISSUE THREAD

**Issue by Luggs123** [1Computer1/riichi-tracker#1]
If the device the app is running on changes from Landscape mode to Portrait mode, the center element of Compass Mode (that is, the one that contains the current hand, settings, etc.) will often end up parallel to the bottom of the screen. As a result, it obscures most of the Riichi buttons for the players on the left and/or right sides of the screen.

**Comment by Luggs123** [comment]
Sure. I’m using iOS with the Web App having been installed, so it’s most likely running through Safari.

![818D5F66-F740-4CEB-97BF-E575D967EC53](https://user-images.githubusercontent.com/15039493/189164696-9b6d5d26-46e3-4c94-99c1-a61423b2e8ff.jpeg)

**Comment by 1Computer1** [comment]
I don't have an iOS device so this will be tough to test. Could you check the latest version of the site?

**Comment by Luggs123** [comment]
Looks to be fixed, though it seems like on both iOS and on Chrome on my PC that the icon to go back to the main menu no longer shows (only affects the Compass view).

**Comment by 1Computer1** [comment]
Oh, that should've been fixed with the changes right afterwards.

**Comment by Luggs123** [comment]
Yup, looks like it's indeed all fixed.
